branch-defaults:
  default:
    environment: flask-env-5
environment-defaults:
  flask-env-5:
    branch: null
    repository: null
global:
  application_name: flask-tutorial-2
  default_ec2_keyname: owen
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
